# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_2/basys.xdc

# IP: ip/bird/bird.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bird || ORIG_REF_NAME==bird}]

# IP: ip/back/back.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==back || ORIG_REF_NAME==back}]

# IP: ip/bird0/bird0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bird0 || ORIG_REF_NAME==bird0}]

# IP: ip/bird2/bird2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bird2 || ORIG_REF_NAME==bird2}]

# IP: ip/pipe/pipe.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pipe || ORIG_REF_NAME==pipe}]

# XDC: ip/bird/bird_ooc.xdc

# XDC: ip/back/back_ooc.xdc

# XDC: ip/bird0/bird0_ooc.xdc

# XDC: ip/bird2/bird2_ooc.xdc

# XDC: ip/pipe/pipe_ooc.xdc
