# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/final/project_new/project_2.cache/wt [current_project]
set_property parent.project_path E:/FPGA/final/project_new/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/coe/pipe.coe
add_files E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/coe/bird.coe
add_files E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/coe/back.coe
add_files E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/coe/bird0.coe
add_files E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/coe/bird2.coe
read_ip E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird/bird.xci
set_property used_in_implementation false [get_files -all e:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird/bird_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird/bird.xci]

read_ip E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/back/back.xci
set_property used_in_implementation false [get_files -all e:/FPGA/final/project_new/project_2.srcs/sources_1/ip/back/back_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/back/back.xci]

read_ip E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird0/bird0.xci
set_property used_in_implementation false [get_files -all e:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird0/bird0_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird0/bird0.xci]

read_ip E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird2/bird2.xci
set_property used_in_implementation false [get_files -all e:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird2/bird2_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/bird2/bird2.xci]

read_ip E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/pipe/pipe.xci
set_property used_in_implementation false [get_files -all e:/FPGA/final/project_new/project_2.srcs/sources_1/ip/pipe/pipe_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/final/project_new/project_2.srcs/sources_1/ip/pipe/pipe.xci]

read_verilog -library xil_defaultlib {
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/ff_lib.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/one_pulse.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/rs232.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/DSP.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/timer_1ms.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/calpostion.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/calpos_back.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/calpos_pipe.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/expand.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/button.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/vga_640x480.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/status.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/running.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/pipeControl.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/pbdebounce.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/display.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/clkdiv.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/calScore.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/calculateXY.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/draw.v
  E:/FPGA/final/project_new/project_2.srcs/sources_1/imports/flapyBird/top.v
}
read_xdc E:/FPGA/final/project_new/project_2.srcs/constrs_1/imports/project_2/basys.xdc
set_property used_in_implementation false [get_files E:/FPGA/final/project_new/project_2.srcs/constrs_1/imports/project_2/basys.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
